### ISSUE TITLE
Add support for source maps in production

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/web3-starter#18]
**Is your feature request related to a problem? Please describe.**
Add source maps for production builds.

**Describe the solution you'd like**
Modify the next.config.js as per the [official documentation](https://nextjs.org/docs/advanced-features/source-maps) to add 

```diff 
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
+ productionBrowserSourceMaps: true,
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
};
```

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by nickytonline** [comment]
Hi @teezzan, just checking in to see if you're still working on this.

**Comment by teezzan** [comment]
I will do it right away. Sorry for taking so long.

**Comment by nickytonline** [comment]
@teezzan, no rush. 😎

I was just checking in.
