### ISSUE TITLE
Add the @openzeppelin/contracts package to the project

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/web3-starter#21]
**Is your feature request related to a problem? Please describe.**
Add the `@openzeppelin/contracts` package to the project.

**Describe the solution you'd like**
Run `yarn add @openzeppelin/contracts` in the root folder of the project. It won't be used by anything yet, but it will be available to folks once they write smart contracts that need to inherit from the contract standards ERC20 and ERC721. It will also allow them to call other contracts.

For more information, check out the [Open Zeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) project.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by LeoUCon** [comment]
@nickytonline  can I grab this?

**Comment by nickytonline** [comment]
Assigned it to you @LeoUCon!
