### ISSUE TITLE
Add the Base64 library to make it available to Solidity smart contracts

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/web3-starter#22]
**Is your feature request related to a problem? Please describe.**
I've been working on Buildspace projects and one thing that seems to pop up a few times is Base64 encoding in Solidity smart contracts. It's not available natively, but someone has created it for the community. The code for this is available in https://gist.github.com/farzaa/f13f5d9bda13af68cc96b54851345832. Shout to @derekchiang for implementing this in https://github.com/derekchiang/loot-name/blob/main/contracts/LootName.sol.

**Describe the solution you'd like**
Create the `/contracts/libraries/Base64.sol` file and paste the content from the gist above. The Base64 library won't be used initially.

A note about it could be mentioned in the sample contract file potentially. or even better the import commented out.

You can see an example of the import in the so-minty project, https://github.com/nickytonline/so-minty/blob/3b457faa63b7d0f4f312c7b26da51ef7ccee4085/contracts/SoMinty.sol#L12

**Describe alternatives you've considered**

**Additional context**

**Comment by LeoUCon** [comment]
I can also go with this

**Comment by nickytonline** [comment]
Assigned it to you @LeoUCon
