### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/web3-starter#26]
**Describe the bug**

Add package-lock.json to .gitignore with a comment saying it's ignored because the project uses yarn.

**To Reproduce**

1. Run `npm install`
2. A `package-lock.json` file is generated.
3. Run `git add`
4. Run `git status`
5. Notice that the `package-lock.json` file is staged for commit.

**Expected behavior**

If `npm install` is run and commits are staged, `package-lock.json` should not be part of the staged files.

**Screenshots**

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

**Comment by nickytonline** [comment]
@crislanarafael, you mentioned that you were looking to work on an issue to get started on this project. Would you like to work on this?

**Comment by s-blais** [comment]
I can do this!

**Comment by nickytonline** [comment]
Assigned this to you @s-blais!

**Comment by s-blais** [comment]
Thank you! True to its label, this actually was my _first_ issue PR!
